### ISSUE TITLE
Question about quine3

### ISSUE THREAD

**Issue by TheThirdOne** [itchyny/brainfuck#1]
quine3 is an impressively short quine. The next shortest quine I have seen is ~800 characters.

I am interested in understanding the data encoding method you used. I haven't seen the number of `>`s used to encode data before. 

Could you explain the format of the data storage or how the following decoder works?
```
[[>>+[>]+>+[<]<-]>>[>]<+<+++[<]<<+]
```

**Comment by itchyny** [comment]
Sorry but I'm not the author of that quine. I think I just googled and included as a test case 7 years ago. The original author of that quine is @shinh at https://keisukenakano.hatenablog.com/entry/20070618/1182092555 (commented in Japanese), who is famous for http://golf.shinh.org/ and [ELVM](https://github.com/shinh/elvm). How the quine works is explained at https://keisukenakano.hatenablog.com/entry/20070626/1182879045, but it's in Japanese so I'd write here in short.
The characters are represented with two numbers using `a[0] + 16 * a[1] + 43`. For example, `a = [0, 0]` for `'+' = 43`, `a = [3, 1]` for `'>' = 62`. For example, after running the following code
```
-
>+>+++>++>+
+[[>>+[>]+>+[<]<-]>>[>]<+<+++[<]<<+]
```
the memory becomes `[0,0,2,4,3,2, 1,1,4,2, 1,1,1,1,4,2, 1,1,1,1,1,1,4,2, 1,1,4,2]` and reading with the `a[0] + 16 * a[1] + 43` formula (note that the numbers are incremented by 1 to move around with `[>]`, `[<]`) from right to left, it emits `>+>+++>++>+`, which is the second line of the code. The `[>>+[>]+>+[<]<-]` part creates the sequence of `1,1` repeated by the value in the memory and `<+<+++` increments `1,1` to `4,2`. The code `[+[<++++++++++++++++>-]<++++++++++.<]` calculates the character value from `[a[0]+1, a[1]+1]` to `(a[0]+1) + 16 * (a[1]+1+1) + 10` and prints out.

**Comment by itchyny** [comment]
Sorry but I'm not the author of that quine. I think I just googled and included as a test case 7 years ago. The original author of that quine is KeisukeNakano and refined by @shinh https://keisukenakano.hatenablog.com/entry/20070618/1182092555 (commented in Japanese), who is famous for http://golf.shinh.org/ and [ELVM](https://github.com/shinh/elvm). How the quine works is explained at https://keisukenakano.hatenablog.com/entry/20070626/1182879045, but it's in Japanese so I'd write here in short.
The characters are represented with two numbers using `a[0] + 16 * a[1] + 43`. For example, `a = [0, 0]` for `'+' = 43`, `a = [3, 1]` for `'>' = 62`. For example, after running the following code
```
-
>+>+++>++>+
+[[>>+[>]+>+[<]<-]>>[>]<+<+++[<]<<+]
```
the memory becomes `[0,0,2,4,3,2, 1,1,4,2, 1,1,1,1,4,2, 1,1,1,1,1,1,4,2, 1,1,4,2]` and reading with the `a[0] + 16 * a[1] + 43` formula (note that the numbers are incremented by 1 to move around with `[>]`, `[<]`) from right to left, it emits `>+>+++>++>+`, which is the second line of the code. The `[>>+[>]+>+[<]<-]` part creates the sequence of `1,1` repeated by the value in the memory and `<+<+++` increments `1,1` to `4,2`. The code `[+[<++++++++++++++++>-]<++++++++++.<]` calculates the character value from `[a[0]+1, a[1]+1]` to `(a[0]+1) + 16 * (a[1]+1+1) + 10` and prints out.

**Comment by TheThirdOne** [comment]
Thanks for the explanation and the links.

I don't fully understand the decoding yet, but I should be able to figure it out with a little time.
